# fly.toml app configuration file generated for spend-parser on 2025-05-02T23:26:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spend-parser'
primary_region = 'arn'

[build]

[[mounts]]
  source = 'tmp'
  destination = '/tmp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
